[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { workspace = true, features = ["secrets", "json"] }
rocket_dyn_templates = { version = "0.2", features = ["handlebars"] }
serde = { workspace = true }
argon2 = { workspace = true }
