[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { workspace = true }
rocket_dyn_templates = { version = "0.2", features = ["handlebars"] }
base64 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
