[package]
name = "codequest-quest-service"
version = "0.1.0"
edition = "2024"

[dependencies]
codequest-common = { path = "../common/" }
rocket = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["rc"] }
reqwest = { workspace = true, features = ["json"] }
